#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$ROOT_DIR/dist/AgentQuota.app"
BUILD_INFO="$ROOT_DIR/Sources/AgentQuota/BuildInfo.swift"

cd "$ROOT_DIR"

# Generate BuildInfo.swift from git state
GIT_HASH="$(git -C "$ROOT_DIR" rev-parse --short=7 HEAD 2>/dev/null || echo "unknown")"
GIT_TAG="$(git -C "$ROOT_DIR" describe --tags --exact-match HEAD 2>/dev/null || echo "")"

cat > "$BUILD_INFO" <<EOF
// Auto-generated by build-app.sh — do not edit
enum BuildInfo {
    static let commitHash = "$GIT_HASH"
    static let versionTag: String? = ${GIT_TAG:+"\"$GIT_TAG\""}${GIT_TAG:-"nil"}
    static var displayVersion: String {
        if let tag = versionTag {
            return "\(tag) (\(commitHash))"
        }
        return commitHash
    }
}
EOF

swift build -c release
BIN_DIR="$(swift build -c release --show-bin-path)"

rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"
cp "$BIN_DIR/AgentQuota" "$APP_DIR/Contents/MacOS/AgentQuota"
cp "$ROOT_DIR/Resources/Info.plist" "$APP_DIR/Contents/Info.plist"

codesign --force --deep --sign - "$APP_DIR" >/dev/null 2>&1 || true

echo "Built $APP_DIR  ($GIT_HASH${GIT_TAG:+ · $GIT_TAG})"
